apiVersion: fabricator.cestus.io/v1alpha1
kind: Config
components:
  - name: blaze
    generator: fabricator-generate-project-go
    spec:
      goModule: code.cestus.io/blaze
      repoURL: https://github.com/CestusIO/blaze.git
      isTool: true
  - name: "fabricator generate"
    generator: fabricator-generate-go
    spec:
      packageName: blaze
