stages:
  - prepare
  - build
  - test
  - manage
  - store

before_script: []
variables:
  IMAGE_NAME: blaze


automr:
  stage: prepare
  image: registry.gitlab.com/cestus/ci/runner-base:latest
  variables:
    GIT_STRATEGY: none
  before_script: []   # We do not need any setup work, let's remove the global one (if any)
  script:
    - cihelper auto-mr --repo=$CI_PROJECT_ID --source=$CI_COMMIT_REF_NAME --title="${CI_COMMIT_TITLE}" --description="${CI_COMMIT_DESCRIPTION}" --assignee=$GITLAB_USER_ID
  except:
    - master
    - tags

determineVersion:
  stage: prepare
  image: registry.gitlab.com/cestus/ci/runner-base:latest
  before_script: []   # We do not need any setup work, let's remove the global one (if any)
  script:
    - export tag=$(git describe --tags)
    - export buildcounter=${CI_COMMIT_SHORT_SHA}
    - svermaker g $tag
    - . buildhelper.tmp
  artifacts:
    paths:
      - buildhelper.tmp
    expire_in: 45 days

build:
  image: registry.gitlab.com/cestus/ci/runner-go:latest
  stage: build
  cache: &build_cache
    key: build
    paths:
      - .cache
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH=$GOPATH/bin:$PATH
    - . buildhelper.tmp
    - make build_all

  artifacts:
    paths:
      - bin
      - buildhelper.tmp
      - Dockerfile
    expire_in: 1 day

test:
  image: registry.gitlab.com/cestus/ci/runner-go:latest
  stage: test
  cache: *build_cache
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH=$GOPATH/bin:$PATH
    - . buildhelper.tmp
    - make test

autotag:
  stage: manage
  image: registry.gitlab.com/cestus/ci/runner-base:latest
  before_script: []   # We do not need any setup work, let's remove the global one (if any)
  script:
    - . buildhelper.tmp
    - cihelper auto-tag --repo=$CI_PROJECT_ID --commit=$CI_COMMIT_SHA --tag=$goModuleBuildVersion --isRelease=$svermakerRelease
  except:
    - tags
  only:
    - master

publish_artifact:
  image: registry.gitlab.com/cestus/ci/runner-base:latest
  stage: store
  before_script: []
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  artifacts:
    paths:
      - bin
    expire_in: 50yrs
  script:
    - ls -la
  only:
    - tags

publish_artifact_manual:
  image: registry.gitlab.com/cestus/ci/runner-base:latest
  stage: store
  before_script: []
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  artifacts:
    paths:
      - bin
    expire_in: 50yrs
  script:
    - ls -la
  when: manual
  except:
    - tags