.PHONY: generate
## Install tools
all: 
	go install github.com/google/wire/cmd/wire@v0.5.0
	go install github.com/matryer/moq@v0.2.1
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0
	go install github.com/onsi/ginkgo/v2/ginkgo@v2.0.0
	go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
