//go:build tools
// +build tools

// Code generated by fabricator-generate-service-go
//
// Modifications in code regions will be lost during regeneration!

package tools

// region CODE_REGION(TOOL_DEPENDENCY)

import (
	_ "github.com/google/wire"

	_ "github.com/google/wire/cmd/wire"

	_ "github.com/onsi/ginkgo/v2/ginkgo"
)

// endregion